[[redirects]]
  from = "/posts/hello-world"
  to = "https://reviewsworld.net/successful-popular-k-pop-idols/"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
